logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.sunglowsys: DEBUG

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialact